publicdata:
  employment:
    data_api-key: ${PUBLIC_DATA_EMPLOYMENT_ENCODING_API}
    base-url: ${PUBLIC_DATA_EMPLOYMENT_BASE_URL}
crawler:
  chrome:
    binary-path: ${USER_BINARY_PATH}
    driver-path: ${USER_DRIVER_PATH}
    user-agent: ${USER_AGENT}

  remember:
    base-url: ${REMEMBER_BASEURL}
    list-selector: ${REMEMBER_LIST_SELECTOR}
    wait-millis: ${REMEMBER_WAIT_MILLIS}